// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetHomeDir():Promise<string>;

export function GetOrCreateCacheDir():Promise<string>;

export function GetOrCreateConfig():Promise<main.Config>;

export function Greet(arg1:string):Promise<string>;

export function JoinPath(arg1:Array<string>):Promise<string>;

export function PickDirectory(arg1:string):Promise<string>;

export function ResetConfig():Promise<main.Config>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SplitPath(arg1:string):Promise<Array<string>>;

export function WalkDir(arg1:string):Promise<Array<string>>;
