// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetOrCreateCacheDir() {
  return window['go']['main']['App']['GetOrCreateCacheDir']();
}

export function GetOrCreateConfig() {
  return window['go']['main']['App']['GetOrCreateConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function JoinPath(arg1) {
  return window['go']['main']['App']['JoinPath'](arg1);
}

export function PickDirectory(arg1) {
  return window['go']['main']['App']['PickDirectory'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SplitPath(arg1) {
  return window['go']['main']['App']['SplitPath'](arg1);
}

export function WalkDir(arg1) {
  return window['go']['main']['App']['WalkDir'](arg1);
}
